### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by phanirithvij** [EgoistDeveloper/Wallppr#1]
Hi, I wasn't able to run the binary from the releases on windows 10 x64.

So I tried building in visual studio 2019 (I'm a beginner in C#, visual studio) and got these errors

```cs
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'KOR' could not be found (are you missing a using directive or an assembly reference?)	Wallppr	D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\Data\Setup.cs	9	Active
```

```cs
using KOR.ReleaseCheck;
```

I tried searching for kor and found this https://github.com/korproject
But there was no `ReleaseCheck` anywhere https://github.com/search?q=org%3Akorproject+ReleaseCheck

I was wondering how I can get it working.

**Comment by relliv** [comment]
@phanirithvij Hi, sorry I forgot Release Check part migrating. I added into solution and some lines added to comment block (for now). You can get build now, please check last commits.

**Comment by phanirithvij** [comment]
I get this now

![image](https://user-images.githubusercontent.com/29627898/106270977-ca8dd600-6254-11eb-9241-adb27a5064e2.png)

**Comment by relliv** [comment]
@phanirithvij what is you device specs and environment info. And I need you debug output logs.

![image](https://user-images.githubusercontent.com/17010054/106307973-1babc300-6271-11eb-82ca-6c6cd88cc694.png)

**Comment by phanirithvij** [comment]
<details>
<summary>Output log</summary>

```cs
'Wallppr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. 
'Wallppr.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Wallppr.exe'. Symbols loaded.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\LoadingIndicators.WPF.dll'. Symbols loaded.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.EntityFrameworkCore.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Module was built without symbols.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\GalaSoft.MvvmLight.dll'. Symbols loaded.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ObjectModel\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.ObjectModel.dll'. Module was built without symbols.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\System.Interactive.Async.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll'. Module was built without symbols.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.DependencyInjection.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Logging.Abstractions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Logging.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Remotion.Linq.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.EntityFrameworkCore.Abstractions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\System.Diagnostics.DiagnosticSource.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Caching.Memory.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Options.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Caching.Abstractions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Primitives.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\SQLitePCLRaw.provider.e_sqlite3.dll'. Module was built without symbols.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\SQLitePCLRaw.core.dll'. Module was built without symbols.
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.EntityFrameworkCore.Sqlite.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.EntityFrameworkCore.Relational.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\System.ComponentModel.Annotations.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\System.Collections.Immutable.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Extensions.Configuration.Abstractions.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.Wrapper.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\Microsoft.Data.Sqlite.dll'. 
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\bin\Debug\SQLitePCLRaw.batteries_v2.dll'. Module was built without symbols.
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
'Wallppr.exe' (CLR v4.0.30319: Wallppr.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. 
Exception thrown: 'System.ArgumentException' in PresentationFramework.dll
Exception thrown: 'System.InvalidOperationException' in PresentationFramework.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>Wallppr.exe</AppDomain><Exception><ExceptionType>System.InvalidOperationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Cannot set Owner property to a Window that has not been shown previously.</Message><StackTrace>   at System.Windows.Window.set_Owner(Window value)
   at Wallppr.Dialogs.DialogWindow.ShowDialogWindow[T](T viewModel, Window owner) in D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\Dialogs\Base\DialogWindow.cs:line 11
   at Wallppr.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs args) in D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\App.xaml.cs:line 62
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp;amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Wallppr.App.Main()</StackTrace><ExceptionString>System.InvalidOperationException: Cannot set Owner property to a Window that has not been shown previously.
   at System.Windows.Window.set_Owner(Window value)
   at Wallppr.Dialogs.DialogWindow.ShowDialogWindow[T](T viewModel, Window owner) in D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\Dialogs\Base\DialogWindow.cs:line 11
   at Wallppr.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs args) in D:\Projects\Experiments\Visual Studio\Wallppr\Wallppr\Wallppr\App.xaml.cs:line 62
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp;amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Wallppr.App.Main()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll
Cannot set Owner property to a Window that has not been shown previously.

``` 

</details>

<details>
<summary>Specs</summary>

Device
```
Device name	RithvijL
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	8.00 GB (7.84 GB usable)
Device ID	A63DAD78-A62E-4BE0-B7CD-163F9E398D3D
Product ID	00342-41372-11937-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
Os
```
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎8/‎7/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0
```

</details>


<details>
<summary>Environment</summary>

```

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA759
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 10.1 Wizards   10.1
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2019.4.1.19317
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2019.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•IronPython and WPFToolkit used under Microsoft Public License (Ms-PL) and are Copyright © Microsoft Corporation
•Portions of RadControls for WPF © 2010-2011 by Telerik Corporation.  All rights reserved.
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•QtSingleApplication Copyright 2013 Digia Plc and/or its subsidiary(-ies).
•Font Awesome Copyright 2018 Fonticons, Inc.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2019.4.1.19317
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

</details>

**Comment by relliv** [comment]
Fixed with [set app setup priority](https://github.com/EgoistDeveloper/Wallppr/commit/14552f33b3597e6db097e7eacb0e6526af49faf1)
